-- Feature-level feedback tracking
-- This tracks WHICH SPECIFIC features (not just types) users like/dislike
-- e.g., "Tom Cruise" (actor), "superhero" (keyword), "Marvel Cinematic Universe" (collection)

-- Create table to track specific feature feedback
create table if not exists user_feature_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  feature_type text not null check (feature_type in ('actor', 'director', 'keyword', 'genre', 'collection', 'studio', 'franchise')),
  feature_id integer not null, -- TMDB ID for the feature (person_id, keyword_id, collection_id, etc.)
  feature_name text not null, -- Human-readable name
  positive_count integer default 0, -- Times user clicked "More Like This" on movies with this feature
  negative_count integer default 0, -- Times user clicked "Not Interested" on movies with this feature
  inferred_preference numeric(4,3) default 0.5, -- -1.0 to 1.0, calculated from counts
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, feature_type, feature_id)
);

-- Enable RLS
alter table user_feature_feedback enable row level security;

-- Policies
create policy "Users can read their own feature feedback"
  on user_feature_feedback for select
  using (auth.uid() = user_id);

create policy "Users can update their own feature feedback"
  on user_feature_feedback for update
  using (auth.uid() = user_id);

create policy "Users can insert their own feature feedback"
  on user_feature_feedback for insert
  with check (auth.uid() = user_id);

-- Indexes for faster lookups
create index if not exists user_feature_feedback_user_id_idx on user_feature_feedback (user_id);
create index if not exists user_feature_feedback_type_idx on user_feature_feedback (feature_type);
create index if not exists user_feature_feedback_lookup_idx on user_feature_feedback (user_id, feature_type, feature_id);

-- Comments
comment on table user_feature_feedback is 'Tracks user preferences for specific features (actors, keywords, franchises) based on feedback';
comment on column user_feature_feedback.inferred_preference is 'Calculated preference: negative_count / (positive + negative), mapped to -1 to 1 range. Below 0.3 = avoid, above 0.7 = prefer';

-- Also add a column to suggestion_feedback to store the extracted features for later analysis
alter table suggestion_feedback 
add column if not exists movie_features jsonb default '{}';

comment on column suggestion_feedback.movie_features is 'Extracted features from the rejected/liked movie: {actors: [...], keywords: [...], collection: {...}, etc.}';
