-- Ensure user_feature_feedback table and policies exist (idempotent)
create table if not exists user_feature_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  feature_type text not null check (feature_type in ('actor','director','keyword','genre','collection','studio','franchise')),
  feature_id integer not null,
  feature_name text not null,
  positive_count integer default 0,
  negative_count integer default 0,
  inferred_preference numeric(4,3) default 0.5,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, feature_type, feature_id)
);

alter table user_feature_feedback enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Users can read their own feature feedback') then
    create policy "Users can read their own feature feedback" on user_feature_feedback for select using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can update their own feature feedback') then
    create policy "Users can update their own feature feedback" on user_feature_feedback for update using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Users can insert their own feature feedback') then
    create policy "Users can insert their own feature feedback" on user_feature_feedback for insert with check (auth.uid() = user_id);
  end if;
end $$;

create index if not exists user_feature_feedback_user_id_idx on user_feature_feedback (user_id);
create index if not exists user_feature_feedback_type_idx on user_feature_feedback (feature_type);
create index if not exists user_feature_feedback_lookup_idx on user_feature_feedback (user_id, feature_type, feature_id);

comment on table user_feature_feedback is 'Tracks user preferences for specific features (actors, keywords, franchises) based on feedback';
comment on column user_feature_feedback.inferred_preference is 'Calculated preference: negative_count / (positive + negative), mapped to -1 to 1 range. Below 0.3 = avoid, above 0.7 = prefer';;
