-- Add reason_types column to suggestion_feedback for tracking which reason types led to the feedback
-- This helps learn which reason types work best for each user

-- Add reason_types array column (stores types like 'director', 'genre', 'actor', 'keyword', 'studio')
alter table suggestion_feedback 
add column if not exists reason_types text[] default '{}';

-- Create a table to store aggregated reason success rates per user
create table if not exists user_reason_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  reason_type text not null check (reason_type in ('director', 'genre', 'actor', 'keyword', 'studio', 'collection', 'decade', 'theme', 'recent')),
  success_count integer default 0,
  total_count integer default 0,
  success_rate numeric(4,3) default 0.5,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, reason_type)
);

-- Enable RLS
alter table user_reason_preferences enable row level security;

-- Policies for user_reason_preferences
create policy "Users can read their own reason preferences"
  on user_reason_preferences for select
  using (auth.uid() = user_id);

create policy "Users can update their own reason preferences"
  on user_reason_preferences for update
  using (auth.uid() = user_id);

create policy "Users can insert their own reason preferences"
  on user_reason_preferences for insert
  with check (auth.uid() = user_id);

-- Index for faster lookups
create index if not exists user_reason_preferences_user_id_idx on user_reason_preferences (user_id);
create index if not exists user_reason_preferences_type_idx on user_reason_preferences (reason_type);

-- Comment
comment on table user_reason_preferences is 'Tracks which recommendation reason types (director match, genre match, etc.) work best for each user based on their feedback';
comment on column suggestion_feedback.reason_types is 'Array of reason types that led to this suggestion (e.g., director, genre, actor)';
