-- Track pairwise comparison events for analysis and learning
create table if not exists pairwise_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  winner_tmdb_id integer not null,
  loser_tmdb_id integer not null,
  shared_reason_tags text[] default '{}',
  winner_sources text[] default '{}',
  loser_sources text[] default '{}',
  winner_consensus text,
  loser_consensus text,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table pairwise_events enable row level security;

create policy "Users can read their own pairwise events"
  on pairwise_events for select
  using (auth.uid() = user_id);

create policy "Users can insert their own pairwise events"
  on pairwise_events for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own pairwise events"
  on pairwise_events for update
  using (auth.uid() = user_id);

create index if not exists pairwise_events_user_idx on pairwise_events (user_id);
create index if not exists pairwise_events_created_idx on pairwise_events (created_at desc);
create index if not exists pairwise_events_pair_idx on pairwise_events (winner_tmdb_id, loser_tmdb_id);
