-- =============================================================================
-- Migration: Create film_diary_events_raw table and fix diary event pipeline
-- =============================================================================
-- Context:
--   The original film_diary_events was a TABLE (schema.sql) but migration
--   20260125223141 replaced it with a VIEW on film_events + film_tmdb_map.
--   This broke diary.ts upsertDiaryEvents() which tried to INSERT into a VIEW.
--
-- This migration:
--   1. Drops the broken film_diary_events VIEW
--   2. Creates film_diary_events_raw TABLE for individual diary entries
--   3. Adds a trigger to sync film_events.last_date on insert/update
--   4. Updates film_diary_events_enriched to COALESCE dates from raw table
--   5. Updates delete_user_data function to reference the new table
--
-- Bug 3 note: film_events has PRIMARY KEY (user_id, uri) -- duplicates cannot
-- exist. The onConflict upsert in the import page correctly deduplicates.
-- =============================================================================


-- =============================================================================
-- 1) Drop the old film_diary_events VIEW
-- =============================================================================

DROP VIEW IF EXISTS public.film_watch_counts;
DROP VIEW IF EXISTS public.film_diary_events CASCADE;


-- =============================================================================
-- 2) Create the real film_diary_events_raw table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.film_diary_events_raw (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  uri         text        NOT NULL,
  watched_date date,
  rating      numeric,
  rewatch     boolean     NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.film_diary_events_raw IS
  'Individual diary watch entries imported from Letterboxd CSV.';

-- Unique constraint: NULLS NOT DISTINCT ensures (user, uri, NULL date, false) = one row
CREATE UNIQUE INDEX IF NOT EXISTS film_diary_events_raw_unique
  ON public.film_diary_events_raw (user_id, uri, watched_date, rewatch)
  NULLS NOT DISTINCT;

CREATE INDEX IF NOT EXISTS film_diary_events_raw_user_idx
  ON public.film_diary_events_raw (user_id);

CREATE INDEX IF NOT EXISTS film_diary_events_raw_user_uri_date_idx
  ON public.film_diary_events_raw (user_id, uri, watched_date DESC NULLS LAST);


-- =============================================================================
-- 3) RLS policies
-- =============================================================================

ALTER TABLE public.film_diary_events_raw ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "diary_raw user read" ON public.film_diary_events_raw;
CREATE POLICY "diary_raw user read"
  ON public.film_diary_events_raw FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "diary_raw user insert" ON public.film_diary_events_raw;
CREATE POLICY "diary_raw user insert"
  ON public.film_diary_events_raw FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "diary_raw user update" ON public.film_diary_events_raw;
CREATE POLICY "diary_raw user update"
  ON public.film_diary_events_raw FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "diary_raw user delete" ON public.film_diary_events_raw;
CREATE POLICY "diary_raw user delete"
  ON public.film_diary_events_raw FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);


-- =============================================================================
-- 4) Trigger: sync film_events.last_date when diary entries change
-- =============================================================================

CREATE OR REPLACE FUNCTION public.sync_film_events_last_date()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  max_date date;
BEGIN
  -- Find the latest watched_date for this user + film
  SELECT MAX(fdr.watched_date)
    INTO max_date
    FROM public.film_diary_events_raw fdr
   WHERE fdr.user_id = NEW.user_id
     AND fdr.uri     = NEW.uri;

  -- Only update if we have a date and the film_events row exists
  IF max_date IS NOT NULL THEN
    UPDATE public.film_events
       SET last_date   = max_date::text,
           updated_at  = now()
     WHERE user_id = NEW.user_id
       AND uri     = NEW.uri
       AND (last_date IS NULL OR last_date < max_date::text);
  END IF;

  RETURN NEW;
END;
$fn$;

COMMENT ON FUNCTION public.sync_film_events_last_date() IS
  'Trigger: updates film_events.last_date to MAX(watched_date) from film_diary_events_raw.';

DROP TRIGGER IF EXISTS trg_sync_film_events_last_date ON public.film_diary_events_raw;
CREATE TRIGGER trg_sync_film_events_last_date
  AFTER INSERT OR UPDATE ON public.film_diary_events_raw
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_film_events_last_date();


-- =============================================================================
-- 5) Update film_diary_events_enriched to incorporate raw diary data
-- =============================================================================

DROP VIEW IF EXISTS public.film_diary_events_enriched;

CREATE VIEW public.film_diary_events_enriched
WITH (security_invoker = true)
AS
  SELECT
    fe.user_id,
    ftm.tmdb_id,
    COALESCE(
      diary_max.max_watched_date,
      CASE
        WHEN fe.last_date ~ '^\d{4}-\d{2}-\d{2}$' THEN fe.last_date::date
        ELSE NULL::date
      END
    ) AS watched_at,
    fe.rating,
    fe.title,
    fe.year,
    fe.uri,
    fe.liked,
    fe.on_watchlist,
    fe.watch_count,
    fe.rewatch
  FROM public.film_events fe
  JOIN public.film_tmdb_map ftm
    ON ftm.user_id = fe.user_id
   AND ftm.uri     = fe.uri
  LEFT JOIN LATERAL (
    SELECT MAX(fdr.watched_date) AS max_watched_date
      FROM public.film_diary_events_raw fdr
     WHERE fdr.user_id = fe.user_id
       AND fdr.uri     = fe.uri
  ) diary_max ON true;

GRANT SELECT ON public.film_diary_events_enriched TO authenticated;


-- =============================================================================
-- 6) Update delete_user_data function to reference film_diary_events_raw
-- =============================================================================

CREATE OR REPLACE FUNCTION public.delete_user_data(target_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  deleted_blocked integer;
  deleted_mappings integer;
  deleted_events integer;
  deleted_diary integer;
  deleted_feedback integer;
  deleted_exploration integer;
  deleted_adjacent integer;
  deleted_saved integer;
  deleted_reason_prefs integer;
BEGIN
  IF auth.uid() != target_user_id THEN
    RAISE EXCEPTION 'Unauthorized: can only delete your own data';
  END IF;

  DELETE FROM public.blocked_suggestions WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_blocked = ROW_COUNT;

  DELETE FROM public.suggestion_feedback WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_feedback = ROW_COUNT;

  DELETE FROM public.user_exploration_stats WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_exploration = ROW_COUNT;

  DELETE FROM public.user_adjacent_preferences WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_adjacent = ROW_COUNT;

  DELETE FROM public.saved_suggestions WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_saved = ROW_COUNT;

  DELETE FROM public.user_reason_preferences WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_reason_prefs = ROW_COUNT;

  DELETE FROM public.film_tmdb_map WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_mappings = ROW_COUNT;

  -- Delete diary entries from the real table
  BEGIN
    DELETE FROM public.film_diary_events_raw WHERE user_id = target_user_id;
    GET DIAGNOSTICS deleted_diary = ROW_COUNT;
  EXCEPTION WHEN undefined_table THEN
    deleted_diary := 0;
  END;

  DELETE FROM public.film_events WHERE user_id = target_user_id;
  GET DIAGNOSTICS deleted_events = ROW_COUNT;

  RETURN jsonb_build_object(
    'success', true,
    'deleted', jsonb_build_object(
      'blocked_suggestions', deleted_blocked,
      'suggestion_feedback', deleted_feedback,
      'user_exploration_stats', deleted_exploration,
      'user_adjacent_preferences', deleted_adjacent,
      'saved_suggestions', deleted_saved,
      'user_reason_preferences', deleted_reason_prefs,
      'film_tmdb_map', deleted_mappings,
      'film_diary_events', deleted_diary,
      'film_events', deleted_events
    )
  );
END;
$fn$;

GRANT EXECUTE ON FUNCTION public.delete_user_data(uuid) TO authenticated;


-- =============================================================================
-- 7) Reload PostgREST schema cache
-- =============================================================================

NOTIFY pgrst, 'reload schema';
