-- Manual fix migration: Create missing tables and fix RLS policies
-- Addresses production 404/400/403 errors found in logs
-- Safe to run even if objects already exist (idempotent)

-- =============================================================================
-- 1) user_reason_preferences - Tracks which recommendation reason types work best
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.user_reason_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  reason_type TEXT NOT NULL,
  success_count INTEGER DEFAULT 0,
  total_count INTEGER DEFAULT 0,
  success_rate NUMERIC(4,3) DEFAULT 0.5,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, reason_type)
);

COMMENT ON TABLE public.user_reason_preferences IS
'Tracks success rates of different recommendation reason types (genre, actor, director, keyword, etc.) per user for personalization';

ALTER TABLE public.user_reason_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their own reason preferences" ON public.user_reason_preferences;
CREATE POLICY "Users can read their own reason preferences"
  ON public.user_reason_preferences FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own reason preferences" ON public.user_reason_preferences;
CREATE POLICY "Users can update their own reason preferences"
  ON public.user_reason_preferences FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own reason preferences" ON public.user_reason_preferences;
CREATE POLICY "Users can insert their own reason preferences"
  ON public.user_reason_preferences FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS user_reason_preferences_user_id_idx
  ON public.user_reason_preferences (user_id);

CREATE INDEX IF NOT EXISTS user_reason_preferences_type_idx
  ON public.user_reason_preferences (reason_type);


-- =============================================================================
-- 2) user_feature_feedback - Tracks specific feature preferences (actors, keywords, genres)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.user_feature_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  feature_type TEXT NOT NULL,
  feature_id BIGINT NOT NULL,
  feature_name TEXT,
  positive_count INTEGER NOT NULL DEFAULT 0,
  negative_count INTEGER NOT NULL DEFAULT 0,
  inferred_preference NUMERIC(5,4),
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT user_feature_feedback_unique UNIQUE (user_id, feature_type, feature_id)
);

COMMENT ON TABLE public.user_feature_feedback IS
'Feature-level personalization learning: tracks positive/negative feedback per actor, keyword, genre, etc. with Bayesian preference scores';

CREATE INDEX IF NOT EXISTS idx_user_feature_feedback_user_id
  ON public.user_feature_feedback(user_id);

CREATE INDEX IF NOT EXISTS idx_user_feature_feedback_feature_type
  ON public.user_feature_feedback(feature_type);

CREATE INDEX IF NOT EXISTS idx_user_feature_feedback_lookup
  ON public.user_feature_feedback(user_id, feature_type);

ALTER TABLE public.user_feature_feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own feature feedback" ON public.user_feature_feedback;
CREATE POLICY "Users can view own feature feedback"
  ON public.user_feature_feedback FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own feature feedback" ON public.user_feature_feedback;
CREATE POLICY "Users can insert own feature feedback"
  ON public.user_feature_feedback FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own feature feedback" ON public.user_feature_feedback;
CREATE POLICY "Users can update own feature feedback"
  ON public.user_feature_feedback FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own feature feedback" ON public.user_feature_feedback;
CREATE POLICY "Users can delete own feature feedback"
  ON public.user_feature_feedback FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);


-- =============================================================================
-- 3) film_diary_events_enriched - View with TMDB ID mapping for taste profile
-- =============================================================================
-- NOTE: This is handled by migration 20260125130000, so we skip it here to avoid conflicts

-- Migration 20260125130000 already creates this view correctly
-- Skipping to avoid duplicate creation


-- =============================================================================
-- 4) Fix suggestion_feedback RLS policy (403 errors)
-- =============================================================================

-- Ensure RLS is enabled
ALTER TABLE IF EXISTS public.suggestion_feedback ENABLE ROW LEVEL SECURITY;

-- Add default for user_id to prevent client errors
ALTER TABLE IF EXISTS public.suggestion_feedback
  ALTER COLUMN user_id SET DEFAULT auth.uid();

-- Fix INSERT policy to allow authenticated users
DROP POLICY IF EXISTS "Users can insert their own feedback" ON public.suggestion_feedback;
CREATE POLICY IF NOT EXISTS "Users can insert their own feedback"
  ON public.suggestion_feedback
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Ensure other policies exist
DROP POLICY IF EXISTS "Users can read their own feedback" ON public.suggestion_feedback;
CREATE POLICY IF NOT EXISTS "Users can read their own feedback"
  ON public.suggestion_feedback
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);


-- =============================================================================
-- 5) Reload PostgREST schema
-- =============================================================================

NOTIFY pgrst, 'reload schema';
